import type { Api, Model } from "@earendil-works/pi-ai/compat";

/**
 * New models missing from pi-ai 0.82.1. Metadata follows pi-ai 0.85.1 and the
 * provider catalogs; keep the existing adapters and catalog until a full upgrade.
 * Native registry entries take precedence when pi-ai is updated.
 */
export const ADDITIONAL_MODELS: Record<string, Model<Api>> = {
  "openrouter:deepseek/deepseek-v4.1-flash": {
    id: "deepseek/deepseek-v4.1-flash",
    name: "DeepSeek: DeepSeek V4.1 Flash",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: "none",
      minimal: null,
      low: "low",
      medium: null,
      high: "high",
      xhigh: null,
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 0.1,
      output: 0.5,
      cacheRead: 0.01,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 943718,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
      requiresReasoningContentOnAssistantMessages: true,
    },
  },
  "openrouter:z-ai/glm-5.3": {
    id: "z-ai/glm-5.3",
    name: "Z.ai: GLM 5.3",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: null,
      high: "high",
      xhigh: null,
      max: "max",
    },
    input: ["text"],
    cost: {
      input: 0.84,
      output: 2.64,
      cacheRead: 0.156,
      cacheWrite: 0,
    },
    contextWindow: 1310720,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
    },
  },
  "openrouter:z-ai/glm-5.3-flash": {
    id: "z-ai/glm-5.3-flash",
    name: "Z.ai: GLM 5.3 Flash",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: null,
      high: "high",
      xhigh: null,
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 0.15,
      output: 0.5,
      cacheRead: 0.05,
      cacheWrite: 0,
    },
    contextWindow: 1310720,
    maxTokens: 943718,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
    },
  },
  "openrouter:qwen/qwen3.8-max-0902": {
    id: "qwen/qwen3.8-max-0902",
    name: "Qwen: Qwen3.8 Max (0902)",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: "minimal",
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: null,
    },
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.25,
      cacheWrite: 2.5,
    },
    contextWindow: 1000000,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
    },
  },
  "openrouter:qwen/qwen3.8-flash": {
    id: "qwen/qwen3.8-flash",
    name: "Qwen: Qwen3.8 Flash",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.15,
      output: 0.47,
      cacheRead: 0.016,
      cacheWrite: 0.2,
    },
    contextWindow: 1000000,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
    },
  },
  "openrouter:qwen/qwen3.8-27b:free": {
    id: "qwen/qwen3.8-27b:free",
    name: "Qwen: Qwen3.8 27B (free)",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: "none",
      minimal: null,
      low: "low",
      medium: "medium",
      high: null,
      xhigh: "xhigh",
      max: null,
    },
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 235929,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
      supportsStrictMode: true,
      sendSessionAffinityHeaders: true,
    },
  },
  "cerebras:qwen-3.8-27b": {
    id: "qwen-3.8-27b",
    name: "Qwen3.8 27B",
    api: "openai-completions",
    provider: "cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.99,
      output: 1.49,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 65536,
    maxTokens: 32768,
    compat: {
      supportsStore: false,
      supportsDeveloperRole: false,
    },
    thinkingLevelMap: {
      off: "none",
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: null,
      max: null,
    },
  },
  "openai:gpt-6-sol": {
    id: "gpt-6-sol",
    name: "GPT-6 Sol",
    api: "openai-responses",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 10,
      cacheRead: 0.2,
      cacheWrite: 2.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 4,
          output: 15,
          cacheRead: 0.4,
          cacheWrite: 5,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: "none",
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsStrictMode: true,
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
      supportsExplicitPromptCacheMode: true,
    },
  },
  "codex:gpt-6-sol": {
    id: "gpt-6-sol",
    name: "GPT-6 Sol",
    api: "openai-codex-responses",
    provider: "openai-codex",
    baseUrl: "https://chatgpt.com/backend-api",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 10,
      cacheRead: 0.2,
      cacheWrite: 2.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 4,
          output: 15,
          cacheRead: 0.4,
          cacheWrite: 5,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: "none",
      minimal: "low",
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
    },
  },
  "openrouter:openai/gpt-6-sol": {
    id: "openai/gpt-6-sol",
    name: "OpenAI: GPT-6 Sol",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 10,
      cacheRead: 0.2,
      cacheWrite: 2.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 4,
          output: 15,
          cacheRead: 0.4,
          cacheWrite: 5,
        },
      ],
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
    },
  },
  "openai:gpt-6-luna": {
    id: "gpt-6-luna",
    name: "GPT-6 Luna",
    api: "openai-responses",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.1,
      output: 0.5,
      cacheRead: 0.01,
      cacheWrite: 0.125,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 0.2,
          output: 0.75,
          cacheRead: 0.02,
          cacheWrite: 0.25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: "none",
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsStrictMode: true,
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
      supportsExplicitPromptCacheMode: true,
    },
  },
  "codex:gpt-6-luna": {
    id: "gpt-6-luna",
    name: "GPT-6 Luna",
    api: "openai-codex-responses",
    provider: "openai-codex",
    baseUrl: "https://chatgpt.com/backend-api",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.1,
      output: 0.5,
      cacheRead: 0.01,
      cacheWrite: 0.125,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 0.2,
          output: 0.75,
          cacheRead: 0.02,
          cacheWrite: 0.25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: "none",
      minimal: "low",
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
    },
  },
  "openrouter:openai/gpt-6-luna": {
    id: "openai/gpt-6-luna",
    name: "OpenAI: GPT-6 Luna",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 0.1,
      output: 0.5,
      cacheRead: 0.01,
      cacheWrite: 0.125,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 0.2,
          output: 0.75,
          cacheRead: 0.02,
          cacheWrite: 0.25,
        },
      ],
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
    },
  },
  "anthropic:claude-opus-5-5": {
    id: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    api: "anthropic-messages",
    provider: "anthropic",
    baseUrl: "https://api.anthropic.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 4,
      output: 20,
      cacheRead: 0.2,
      cacheWrite: 5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      forceAdaptiveThinking: true,
      supportsStrictTools: true,
      supportsTemperature: false,
    },
    thinkingLevelMap: {
      off: null,
      xhigh: "xhigh",
      max: "max",
    },
  },
  "openrouter:anthropic/claude-opus-5.5": {
    id: "anthropic/claude-opus-5.5",
    name: "Anthropic: Claude Opus 5.5",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 4,
      output: 20,
      cacheRead: 0.2,
      cacheWrite: 5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
      cacheControlFormat: "anthropic",
    },
  },
  "xai:grok-4.7": {
    id: "grok-4.7",
    name: "Grok 4.7",
    api: "openai-responses",
    provider: "xai",
    baseUrl: "https://api.x.ai/v1",
    compat: {
      supportsLongCacheRetention: false,
    },
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.5,
      cacheWrite: 0,
      tiers: [
        {
          inputTokensAbove: 200000,
          input: 4,
          output: 12,
          cacheRead: 1,
          cacheWrite: 0,
        },
      ],
    },
    contextWindow: 500000,
    maxTokens: 500000,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: null,
    },
  },
  "openrouter:x-ai/grok-4.7": {
    id: "x-ai/grok-4.7",
    name: "xAI: Grok 4.7",
    api: "openai-completions",
    provider: "openrouter",
    baseUrl: "https://openrouter.ai/api/v1",
    compat: {
      thinkingFormat: "openrouter",
    },
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.6,
      output: 4.8,
      cacheRead: 0.4,
      cacheWrite: 0,
      tiers: [
        {
          inputTokensAbove: 200000,
          input: 3.2,
          output: 9.6,
          cacheRead: 0.8,
          cacheWrite: 0,
        },
      ],
    },
    contextWindow: 500000,
    maxTokens: 450000,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: null,
    },
  },
  "anthropic:claude-fable-5-1": {
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    api: "anthropic-messages",
    provider: "anthropic",
    baseUrl: "https://api.anthropic.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 0.25,
      cacheWrite: 12.5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      forceAdaptiveThinking: true,
      supportsStrictTools: true,
      supportsTemperature: false,
    },
    thinkingLevelMap: {
      off: null,
      xhigh: "xhigh",
      max: "max",
    },
  },
  "openai:gpt-6-astra": {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    api: "openai-responses",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 20,
          output: 75,
          cacheRead: 2,
          cacheWrite: 25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsStrictMode: true,
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
      supportsExplicitPromptCacheMode: true,
    },
  },
  "codex:gpt-6-astra": {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    api: "openai-codex-responses",
    provider: "openai-codex",
    baseUrl: "https://chatgpt.com/backend-api",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
      tiers: [
        {
          inputTokensAbove: 272000,
          input: 20,
          output: 75,
          cacheRead: 2,
          cacheWrite: 25,
        },
      ],
    },
    contextWindow: 272000,
    maxTokens: 128000,
    thinkingLevelMap: {
      off: null,
      minimal: "low",
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    compat: {
      supportsOpenAIGrammarTools: true,
      supportsToolSearch: true,
    },
  },
  "openrouter:anthropic/claude-fable-5.1": {
    id: "anthropic/claude-fable-5.1",
    name: "Anthropic: Claude Fable 5.1",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 0.25,
      cacheWrite: 12.5,
    },
    contextWindow: 1000000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
      cacheControlFormat: "anthropic",
    },
  },
  "openrouter:openai/gpt-6-astra": {
    id: "openai/gpt-6-astra",
    name: "OpenAI: GPT-6 Astra",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
      max: "max",
    },
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 50,
      cacheRead: 1,
      cacheWrite: 12.5,
    },
    contextWindow: 1050000,
    maxTokens: 128000,
    compat: {
      thinkingFormat: "openrouter",
    },
  },
  "openrouter:google/gemini-3.8-flash": {
    id: "google/gemini-3.8-flash",
    name: "Google: Gemini 3.8 Flash",
    api: "openai-completions",
    baseUrl: "https://openrouter.ai/api/v1",
    provider: "openrouter",
    reasoning: true,
    thinkingLevelMap: {
      off: null,
      minimal: null,
      low: "low",
      medium: "medium",
      high: "high",
      xhigh: null,
      max: null,
    },
    input: ["text", "image"],
    cost: {
      input: 0.75,
      output: 3.75,
      cacheRead: 0.075,
      cacheWrite: 0.041667,
    },
    contextWindow: 1048576,
    maxTokens: 65536,
    compat: {
      supportsDeveloperRole: false,
      thinkingFormat: "openrouter",
    },
  },
};
